# Generated by Django 4.0.4 on 2022-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Malumot', 'verbose_name_plural': 'Malumotlar'},
        ),
        migrations.AddField(
            model_name='info',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
